---

env:
  global:
    - CC_TEST_REPORTER_ID=7e54e7b70ec4e0a020a240842e9090811496e51b991af58c9b9667c7e1643553

language: node_js

node_js:
  - stable

cache:
  directories:
    - node_modules

install:
  - yarn

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - yarn lint
  - yarn build
  - yarn test

after_script:
  - ./cc-test-reporter after-build -t lcov --debug --exit-code $TRAVIS_TEST_RESULT
